version: '3.8'

services:
  app:
    image: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SECRET_KEY: BmIzZV-0M4KRAyfdrCB4mA
      FLASK_APP: src/app.py
      DB_NAME: database     
      DB_PASSWORD: StrongestPasswordPfft
      DB_USER: admin   
      UPLOAD_FOLDER: /usr/src/app/static
      DATABASE_URL: postgresql://admin:StrongestPasswordPfft@postgres/database
    volumes:
      - .:/usr/src/app
    container_name: flask_app
    depends_on:
    - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: StrongestPasswordPfft
      POSTGRES_USER: admin 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres

volumes:
  postgres_data:

